// react icons
import {
  PiBasketThin,
  PiCurrencyDollarSimpleThin,
  PiLayoutLight,
  PiPaperPlaneThin,
  PiPlusSquareThin,
  PiTextBLight,
  PiTextboxLight,
  PiUsersThin,
  PiPowerThin,
  PiTrashSimple,
  PiNewspaperLight,
  PiPencilSimpleLight,
  PiUploadLight,
  PiHeartLight,
  PiClockLight,
  PiLockSimpleOpenLight,
  PiArrowBendRightUpLight,
  PiArrowBendRightDownLight,
  PiBoundingBoxLight,
  PiQuestionLight,
  PiUserLight,
  PiShoppingBagLight,
  PiCheckSquareLight,
  PiShieldCheckLight,
  PiHeadphonesLight,
  PiArrowDownLight,
  PiArrowRightLight,
  PiTwitterLogoLight,
  PiGoogleLogoLight,
  PiInstagramLogoLight,
  PiTelegramLogoLight,
  PiYoutubeLogoLight,
  PiEyeLight,
  PiArrowLeftLight,
  PiCreditCardLight,
  PiPaypalLogoLight,
  PiHandshakeLight,
  PiCoinsLight,
  PiImagesLight,
} from "react-icons/pi";
import { GoHome, GoTasklist } from "react-icons/go";
import { IoIosNotificationsOutline } from "react-icons/io";
import {
  CiDark,
  CiDeliveryTruck,
  CiFilter,
  CiLocationOn,
  CiMenuBurger,
  CiSearch,
  CiSettings,
} from "react-icons/ci";
import { TfiClose } from "react-icons/tfi";
import { FcLike } from "react-icons/fc";

export const images = {
  logo: "/images/logo1.svg",
  authLogin: "/images/auth-login.png",
  authRegister: "/images/auth-register.png",
  person: "/images/man.png",
  notFound: "/images/404.svg",
  notAllowed: "/images/not-allowed.png",
};

export const icons = {
  home: <GoHome />,
  deliveryTruck: <CiDeliveryTruck />,
  dollar: <PiCurrencyDollarSimpleThin />,
  basket: <PiBasketThin />,
  cart: <PiShoppingBagLight />,
  plus: <PiPlusSquareThin />,
  paper: <PiPaperPlaneThin />,
  users: <PiUsersThin />,
  user: <PiUserLight />,
  layout: <PiLayoutLight />,
  textB: <PiTextBLight />,
  textBox: <PiTextboxLight />,
  tasks: <GoTasklist />,
  notification: <IoIosNotificationsOutline />,
  settings: <CiSettings />,
  power: <PiPowerThin />,
  search: <CiSearch />,
  close: <TfiClose />,
  moon: <CiDark />,
  trash: <PiTrashSimple />,
  pen: <PiPencilSimpleLight />,
  document: <PiNewspaperLight />,
  upload: <PiUploadLight />,
  heart: <PiHeartLight />,
  redHeart: <FcLike />,
  clock: <PiClockLight />,
  lock: <PiLockSimpleOpenLight />,
  growArrow: <PiArrowBendRightUpLight />,
  downArrow: <PiArrowDownLight />,
  rightArrow: <PiArrowRightLight />,
  leftArrow: <PiArrowLeftLight />,
  fallingArrow: <PiArrowBendRightDownLight />,
  category: <PiBoundingBoxLight />,
  question: <PiQuestionLight />,
  menu: <CiMenuBurger />,
  checkSquare: <PiCheckSquareLight />,
  shield: <PiShieldCheckLight />,
  headphone: <PiHeadphonesLight />,
  twitter: <PiTwitterLogoLight />,
  google: <PiGoogleLogoLight />,
  instagram: <PiInstagramLogoLight />,
  telegram: <PiTelegramLogoLight />,
  youtube: <PiYoutubeLogoLight />,
  filter: <CiFilter />,
  eye: <PiEyeLight />,
  location: <CiLocationOn />,
  creditCard: <PiCreditCardLight />,
  paypal: <PiPaypalLogoLight />,
  handShake: <PiHandshakeLight />,
  coins: <PiCoinsLight />,
  gallery: <PiImagesLight />,
};

export const menuLinks = [
  {
    title: "Dashboard",
    image: icons.home,
    link: "/dashboard",
  },
  {
    title: "Orders",
    image: icons.deliveryTruck,
    link: "/orders",
  },
  {
    title: "Revenue",
    image: icons.dollar,
    link: "/revenue",
  },
  {
    title: "Products",
    image: icons.basket,
    link: "/products",
  },
  {
    title: "Add Product",
    image: icons.plus,
    link: "/add-product",
  },
  {
    title: "Comments",
    image: icons.paper,
    link: "/comments",
  },
  {
    title: "Users",
    image: icons.users,
    link: "/users",
  },
  {
    title: "Blogs",
    image: icons.textB,
    link: "/blogs",
  },
  {
    title: "Add Blog",
    image: icons.textBox,
    link: "/add-blog",
  },
  {
    title: "Tasks",
    image: icons.tasks,
    link: "/tasks",
  },
  {
    title: "Crypto",
    image: icons.coins,
    link: "/crypto",
  },
  {
    title: "Gallery",
    image: icons.gallery,
    link: "/gallery",
  },
  {
    title: "Account",
    image: icons.settings,
    link: "/account",
  },
];
